appdeisy/config/routes.rb
Rails.application.routes.draw do
  resources :cuestionarios
  resources :fechas
  resources :tipos_datos
  resources :users
  get 'welcome/index'
  root :to => "welcome#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

appdeisy/app/models/fecha.rb
class Fecha < ApplicationRecord
end

appdeisy/app/controllers/fechas_controller.rb
class FechasController < ApplicationController
  before_action :set_fecha, only: [:show, :edit, :update, :destroy]

  # GET /fechas
  # GET /fechas.json
  def index
    @fechas = Fecha.all
  end

  # GET /fechas/1
  # GET /fechas/1.json
  def show
  end

  # GET /fechas/new
  def new
    @fecha = Fecha.new
  end

  # GET /fechas/1/edit
  def edit
  end

  # POST /fechas
  # POST /fechas.json
  def create
    @fecha = Fecha.new(fecha_params)

    respond_to do |format|
      if @fecha.save
        format.html { redirect_to @fecha, notice: 'Fecha was successfully created.' }
        format.json { render :show, status: :created, location: @fecha }
      else
        format.html { render :new }
        format.json { render json: @fecha.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fechas/1
  # PATCH/PUT /fechas/1.json
  def update
    respond_to do |format|
      if @fecha.update(fecha_params)
        format.html { redirect_to @fecha, notice: 'Fecha was successfully updated.' }
        format.json { render :show, status: :ok, location: @fecha }
      else
        format.html { render :edit }
        format.json { render json: @fecha.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fechas/1
  # DELETE /fechas/1.json
  def destroy
    @fecha.destroy
    respond_to do |format|
      format.html { redirect_to fechas_url, notice: 'Fecha was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fecha
      @fecha = Fecha.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fecha_params
      params.require(:fecha).permit(:date, :Hora, :Pregunta, :text)
    end
end

appdeisy/app/helpers/fechas_helper.rb
module FechasHelper
end

appdeisy/app/views/fechas/_form.html.erb
<%= form_with(model: fecha, local: true) do |form| %>
  <% if fecha.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fecha.errors.count, "error") %> prohibited this fecha from being saved:</h2>

      <ul>
      <% fecha.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :Hora %>
    <%= form.time_select :Hora %>
  </div>

  <div class="field">
    <%= form.label :Pregunta %>
    <%= form.text_field :Pregunta %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

appdeisy/app/views/fechas/edit.html.erb
<h1>Editing Fecha</h1>

<%= render 'form', fecha: @fecha %>

<%= link_to 'Show', @fecha %> |
<%= link_to 'Back', fechas_path %>

appdeisy/app/views/fechas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fechas</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Hora</th>
      <th>Pregunta</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fechas.each do |fecha| %>
      <tr>
        <td><%= fecha.date %></td>
        <td><%= fecha.Hora %></td>
        <td><%= fecha.Pregunta %></td>
        <td><%= fecha.text %></td>
        <td><%= link_to 'Show', fecha %></td>
        <td><%= link_to 'Edit', edit_fecha_path(fecha) %></td>
        <td><%= link_to 'Destroy', fecha, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fecha', new_fecha_path %>

appdeisy/app/views/fechas/new.html.erb
<h1>New Fecha</h1>

<%= render 'form', fecha: @fecha %>

<%= link_to 'Back', fechas_path %>

appdeisy/app/views/fechas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @fecha.date %>
</p>

<p>
  <strong>Hora:</strong>
  <%= @fecha.Hora %>
</p>

<p>
  <strong>Pregunta:</strong>
  <%= @fecha.Pregunta %>
</p>

<p>
  <strong>Text:</strong>
  <%= @fecha.text %>
</p>

<%= link_to 'Edit', edit_fecha_path(@fecha) %> |
<%= link_to 'Back', fechas_path %>