appdeisy/config/routes.rb
Rails.application.routes.draw do
  resources :cuestionarios
  resources :fechas
  resources :tipos_datos
  resources :users
  get 'welcome/index'
  root :to => "welcome#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

appdeisy/app/models/tipos_dato.rb
class TiposDato < ApplicationRecord
end

appdeisy/app/controllers/tipos_datos_controller.rb
class TiposDatosController < ApplicationController
  before_action :set_tipos_dato, only: [:show, :edit, :update, :destroy]

  # GET /tipos_datos
  # GET /tipos_datos.json
  def index
    @tipos_datos = TiposDato.all
  end

  # GET /tipos_datos/1
  # GET /tipos_datos/1.json
  def show
  end

  # GET /tipos_datos/new
  def new
    @tipos_dato = TiposDato.new
  end

  # GET /tipos_datos/1/edit
  def edit
  end

  # POST /tipos_datos
  # POST /tipos_datos.json
  def create
    @tipos_dato = TiposDato.new(tipos_dato_params)

    respond_to do |format|
      if @tipos_dato.save
        format.html { redirect_to @tipos_dato, notice: 'Tipos dato was successfully created.' }
        format.json { render :show, status: :created, location: @tipos_dato }
      else
        format.html { render :new }
        format.json { render json: @tipos_dato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipos_datos/1
  # PATCH/PUT /tipos_datos/1.json
  def update
    respond_to do |format|
      if @tipos_dato.update(tipos_dato_params)
        format.html { redirect_to @tipos_dato, notice: 'Tipos dato was successfully updated.' }
        format.json { render :show, status: :ok, location: @tipos_dato }
      else
        format.html { render :edit }
        format.json { render json: @tipos_dato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipos_datos/1
  # DELETE /tipos_datos/1.json
  def destroy
    @tipos_dato.destroy
    respond_to do |format|
      format.html { redirect_to tipos_datos_url, notice: 'Tipos dato was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipos_dato
      @tipos_dato = TiposDato.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipos_dato_params
      params.require(:tipos_dato).permit(:date, :time, :text)
    end
end

appdeisy/app/helpers/tipos_datos_helper.rb
module TiposDatosHelper
end

appdeisy/app/views/tipos_datos/_form.html.erb
<%= form_with(model: tipos_dato, local: true) do |form| %>
  <% if tipos_dato.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tipos_dato.errors.count, "error") %> prohibited this tipos_dato from being saved:</h2>

      <ul>
      <% tipos_dato.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.time_select :time %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

appdeisy/app/views/tipos_datos/edit.html.erb
<h1>Editing Tipos Dato</h1>

<%= render 'form', tipos_dato: @tipos_dato %>

<%= link_to 'Show', @tipos_dato %> |
<%= link_to 'Back', tipos_datos_path %>

appdeisy/app/views/tipos_datos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tipos Datos</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Time</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tipos_datos.each do |tipos_dato| %>
      <tr>
        <td><%= tipos_dato.date %></td>
        <td><%= tipos_dato.time %></td>
        <td><%= tipos_dato.text %></td>
        <td><%= link_to 'Show', tipos_dato %></td>
        <td><%= link_to 'Edit', edit_tipos_dato_path(tipos_dato) %></td>
        <td><%= link_to 'Destroy', tipos_dato, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tipos Dato', new_tipos_dato_path %>

appdeisy/app/views/tipos_datos/new.html.erb
<h1>New Tipos Dato</h1>

<%= render 'form', tipos_dato: @tipos_dato %>

<%= link_to 'Back', tipos_datos_path %>

appdeisy/app/views/tipos_datos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @tipos_dato.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @tipos_dato.time %>
</p>

<p>
  <strong>Text:</strong>
  <%= @tipos_dato.text %>
</p>

<%= link_to 'Edit', edit_tipos_dato_path(@tipos_dato) %> |
<%= link_to 'Back', tipos_datos_path %>