appdeisy/config/routes.rb
Rails.application.routes.draw do
  resources :cuestionarios
  resources :fechas
  resources :tipos_datos
  resources :users
  get 'welcome/index'
  root :to => "welcome#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

appdeisy/app/models/cuestionario.rb
class Cuestionario < ApplicationRecord
end

appdeisy/app/controllers/cuestionarios_controller.rb
class CuestionariosController < ApplicationController
  before_action :set_cuestionario, only: [:show, :edit, :update, :destroy]

  # GET /cuestionarios
  # GET /cuestionarios.json
  def index
    @cuestionarios = Cuestionario.all
  end

  # GET /cuestionarios/1
  # GET /cuestionarios/1.json
  def show
  end

  # GET /cuestionarios/new
  def new
    @cuestionario = Cuestionario.new
  end

  # GET /cuestionarios/1/edit
  def edit
  end

  # POST /cuestionarios
  # POST /cuestionarios.json
  def create
    @cuestionario = Cuestionario.new(cuestionario_params)

    respond_to do |format|
      if @cuestionario.save
        format.html { redirect_to @cuestionario, notice: 'Cuestionario was successfully created.' }
        format.json { render :show, status: :created, location: @cuestionario }
      else
        format.html { render :new }
        format.json { render json: @cuestionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cuestionarios/1
  # PATCH/PUT /cuestionarios/1.json
  def update
    respond_to do |format|
      if @cuestionario.update(cuestionario_params)
        format.html { redirect_to @cuestionario, notice: 'Cuestionario was successfully updated.' }
        format.json { render :show, status: :ok, location: @cuestionario }
      else
        format.html { render :edit }
        format.json { render json: @cuestionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cuestionarios/1
  # DELETE /cuestionarios/1.json
  def destroy
    @cuestionario.destroy
    respond_to do |format|
      format.html { redirect_to cuestionarios_url, notice: 'Cuestionario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cuestionario
      @cuestionario = Cuestionario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cuestionario_params
      params.require(:cuestionario).permit(:fecha, :hora, :pregunta)
    end
end

appdeisy/app/helpers/cuestionarios_helper.rb
module CuestionariosHelper
end

appdeisy/app/views/cuestionarios/_form.html.erb
<%= form_with(model: cuestionario, local: true) do |form| %>
  <% if cuestionario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cuestionario.errors.count, "error") %> prohibited this cuestionario from being saved:</h2>

      <ul>
      <% cuestionario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fecha %>
    <%= form.date_select :fecha %>
  </div>

  <div class="field">
    <%= form.label :hora %>
    <%= form.time_select :hora %>
  </div>

  <div class="field">
    <%= form.label :pregunta %>
    <%= form.text_area :pregunta %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

appdeisy/app/views/cuestionarios/edit.html.erb
<h1>Editing Cuestionario</h1>

<%= render 'form', cuestionario: @cuestionario %>

<%= link_to 'Show', @cuestionario %> |
<%= link_to 'Back', cuestionarios_path %>

appdeisy/app/views/cuestionarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cuestionarios</h1>

<table>
  <thead>
    <tr>
      <th>Fecha</th>
      <th>Hora</th>
      <th>Pregunta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cuestionarios.each do |cuestionario| %>
      <tr>
        <td><%= cuestionario.fecha %></td>
        <td><%= cuestionario.hora %></td>
        <td><%= cuestionario.pregunta %></td>
        <td><%= link_to 'Show', cuestionario %></td>
        <td><%= link_to 'Edit', edit_cuestionario_path(cuestionario) %></td>
        <td><%= link_to 'Destroy', cuestionario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cuestionario', new_cuestionario_path %>

appdeisy/app/views/cuestionarios/new.html.erb
<h1>New Cuestionario</h1>

<%= render 'form', cuestionario: @cuestionario %>

<%= link_to 'Back', cuestionarios_path %>

appdeisy/app/views/cuestionarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha:</strong>
  <%= @cuestionario.fecha %>
</p>

<p>
  <strong>Hora:</strong>
  <%= @cuestionario.hora %>
</p>

<p>
  <strong>Pregunta:</strong>
  <%= @cuestionario.pregunta %>
</p>

<%= link_to 'Edit', edit_cuestionario_path(@cuestionario) %> |
<%= link_to 'Back', cuestionarios_path %>